---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
# Or just use ubuntu/trusty32 or ubuntu/trusty64.
vagrant_box: ubuntu/trusty64
vagrant_user: vagrant

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: local.dev
vagrant_machine_name: drupalvm
vagrant_ip: 192.168.88.88

# Memory and CPU to use for this VM.
vagrant_memory: 512
#cpus amount doesnt work properly on all machines
#for now it is disabled
#vagrant_cpus: 2

# Settings for building a site
site_root_path: "/home/vagrant/{{ vagrant_hostname }}/docroot"
site_domain: "{{ vagrant_hostname }}"
site_mysql_database: local_db
site_mysql_user: local_db_user
site_mysql_password: local_db_pass


# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
apache_vhosts:
  - {servername: "{{ site_domain }}", serveralias: "www.{{ site_domain }}", documentroot: "{{ site_root_path }}"}
  # - {servername: "xhprof.drupalvm.dev", documentroot: "/usr/share/php/xhprof_html"}
  # - {servername: "pimpmylog.drupalvm.dev", documentroot: "/usr/share/php/pimpmylog"}

# MySQL Databases and users. If build_from_makefile is true, first database will
# be used for the makefile-built site.
mysql_databases:
  - name: "{{ site_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ site_mysql_user }}"
    host: "localhost"
    password: "{{ site_mysql_password }}"
    priv: "{{ site_mysql_database }}.*:ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - mailhog
  # - memcached
  # - pimpmylog
  # - solr
  # - varnish
  - xdebug
  # - xhprof

# Add any extra packages you'd like to install.
extra_packages:
  - nfs-kernel-server
  - nfs-common
  - libapache2-mod-php5

# You can configure almost anything else on the server in the rest of this file.
mysql_root_password: root

extra_security_enabled: false

drush_version: master
drush_keep_updated: true
drush_composer_cli_options: "--prefer-dist --no-interaction"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
firewall_log_dropped_packets: false

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.6"
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_enable_php_fpm: false

# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# MySQL Configuration.
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
adminer_add_apache_config: true

# Memory settings (default values optimized ~512MB RAM).
mysql_key_buffer_size: "256M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_myisam_sort_buffer_size: "64M"
mysql_thread_cache_size: "8"
mysql_query_cache_size: "16M"

# Other settings.
mysql_wait_timeout: 28800

# Try number of CPU's * 2 for thread_concurrency.
mysql_thread_concurrency: 2

# InnoDB settings.
# Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
mysql_innodb_file_per_table: "1"
mysql_innodb_buffer_pool_size: "256M"
mysql_innodb_additional_mem_pool_size: "20M"
# Set .._log_file_size to 25% of buffer pool size.
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "1"
mysql_innodb_lock_wait_timeout: 50

# Varnish Configuration.
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug Configuration..
php_xdebug_idekey: phpstorm
php_xdebug_remote_host: 10.0.2.2
php_xdebug_remote_port: "9009"
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_remote_autostart: 0

# Solr Configuration (if enabled above).
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

##########################
#   Swap file settings   #
##########################
swapfile_location: /swapfile
swapfile_size: 512M
